#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "pufferpanel"
name = "PufferPanel"
description.en = "Web-based Game Server Management System"
description.fr = "Système de gestion de serveur de jeu"

version = "2.6.9~ynh2"

maintainers = []

[upstream]
license = "Apache-2.0"
website = "https://www.pufferpanel.com/"
admindoc = "https://docs.pufferpanel.com/en/latest/"
code = "https://github.com/PufferPanel/PufferPanel"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "350M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    help.en = "Admin username minimum length is five characters."
    help.fr = "La longueur minimale du nom d'utilisateur de l'administrateur est de cinq caractères."
    type = "user"

    [install.password]
    type = "password"


[resources]
    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]
    subdirs = [ "binaries", "cache", "servers" ]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.apt]
    packages = "postgresql"

    extras.pufferpanel.repo = "deb https://packagecloud.io/pufferpanel/pufferpanel/debian/ buster main"
    extras.pufferpanel.key = "https://packagecloud.io/pufferpanel/pufferpanel/gpgkey"
    extras.pufferpanel.packages = "pufferpanel"

    [resources.database]
    type = "postgresql"
