#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    arg.password = "password1234"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    # test_upgrade_from.5a4a4ca05f2100d37b87893bd8f6c6eb7341dc50.name = "Upgrade from 2.6.9~ynh2"
