#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

email=$(ynh_user_get_info --username="$admin" --key=mail)

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================
ynh_script_progression "Validating installation parameters..."

if [[ ${#admin} -lt 5 ]]; then
    ynh_die "Admin username minimum length is 5"
fi

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

systemctl enable "$app.service" --quiet

yunohost service add "$app" --description="Web-based Game Server Management System" --log="/var/log/$app/$app.log"

#=================================================
# SPECIFIC SETUP
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config.json" --destination="/etc/$app/config.json"

chmod 650 "/etc/$app/config.json"

pufferpanel user add --admin --email="$email" --name="$admin" --password="$password"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd" --wait_until="Listening for"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
